# Generated by Django 4.2.3 on 2023-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code_barre', models.ImageField(blank=True, upload_to='images/')),
                ('produit_id', models.CharField(editable=False, max_length=4, null=True, unique=True)),
            ],
        ),
    ]
