# Generated by Django 4.2.3 on 2023-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(null=True),
        ),
    ]
