# Generated by Django 4.2.3 on 2023-07-23 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_client_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(null=True)),
                ('montant_total', models.FloatField(editable=False, null=True)),
                ('date_vente', models.DateField(auto_now_add=True, null=True)),
                ('is_modified', models.BooleanField(default=False, editable=False)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(null=True)),
                ('montant_total', models.FloatField(editable=False, null=True)),
                ('date_achat', models.DateField(auto_now_add=True, null=True)),
                ('is_modified', models.BooleanField(default=False, editable=False)),
                ('fournisseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.fournisseur')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.produit')),
            ],
        ),
    ]
